<a href="https://colab.research.google.com/github/GoAshim/Deep-Learning-with-TensorFlow/blob/main/02_Fundamentals_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals of TensorFlow
In this workbook we will not do any project, rather we will work on the fundamental concepts of Tensors using TensorFlow, which is going to help us when we do various Deep Learning projects using Neural Network in TensorFlow in the future workbooks.

We will cover the following concepts in this workbook -
* Introduction to tensors
* Getting information from tensors
* Updating / changing tensors
* Comparing tensor & numpy
* Using @tf function to speed up regular python function
* Using GPU (or TPU) with TensorFlow

### Introduction to tensors

In [2]:
# Import library
import numpy as np
import tensorflow as tf

In [4]:
# Check the current version (as of Feb 3, 2024) of tensorflow
ver = tf.__version__
print(ver)

2.15.0


### Create Tensors

In [7]:
# Create a single value (scalar) constant tensor with value as numpy integer
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
# We see that it's a zero dimension tensor, meaning one constant value is like a point in space having zero dimension
scalar.ndim

0

In [10]:
# Create a vector
vector = tf.constant([3, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [11]:
# We see that it's a one dimension tensor, meaning an array is like a line in space having one dimension
vector.ndim

1

In [12]:
# Create a matrix
matrix1 = tf.constant([[2, 4],
                       [5, 8]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 8]], dtype=int32)>

In [13]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having two dimensions
matrix1.ndim

2

In [14]:
# Create another matrix
matrix2 = tf.constant([[2., 3.],
                       [4., 5.],
                       [6., 7.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float16)>

In [15]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a flat rectangle in space having two dimensions
matrix2.ndim

2

In [17]:
# Create a tensor
tensor1 = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [9, 8, 7]],
                      [[6, 5, 4],
                       [3, 2, 1]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [3, 2, 1]]], dtype=int32)>

In [21]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 2 and hight (or number of elements with rows and columns) = 3.
tensor1.ndim

3

In [19]:
tensor2 = tf.constant([[[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.]],
                       [[9., 8., 7.],
                        [6., 5., 4.],
                        [3., 2., 1.]],
                       [[9., 6., 3.],
                        [8., 5., 2.],
                        [7., 4., 1.]]])
tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]],

       [[9., 6., 3.],
        [8., 5., 2.],
        [7., 4., 1.]]], dtype=float32)>

In [22]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 3 and hight (or number of elements with rows and columns) = 3.
tensor2.ndim

3