<a href="https://colab.research.google.com/github/GoAshim/Deep-Learning-with-TensorFlow/blob/main/02_Fundamentals_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals of TensorFlow
In this workbook we will not do any project, rather we will work on the fundamental concepts of Tensors using TensorFlow, which is going to help us when we do various Deep Learning projects using Neural Network in TensorFlow in the future workbooks.

We will cover the following concepts in this workbook -
* Introduction to tensors
* Getting information from tensors
* Updating / changing tensors
* Comparing tensor & numpy
* Using @tf function to speed up regular python function
* Using GPU (or TPU) with TensorFlow

### Introduction to tensors
In this section we will explore different ways of creating tensors.

In [1]:
# Import library
import numpy as np
import tensorflow as tf

In [2]:
# Check the current version (as of Feb 3, 2024) of tensorflow
ver = tf.__version__
print(ver)

2.15.0


#### Create Tensors from Constants `tf.constant()`

In [3]:
# Create a single value (scalar) constant tensor with value as numpy integer
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
# We see that it's a zero dimension tensor, meaning one constant value is like a point in space having zero dimension
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([3, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [6]:
# We see that it's a one dimension tensor, meaning an array is like a line in space having one dimension
vector.ndim

1

In [7]:
# Create a matrix
matrix1 = tf.constant([[2, 4],
                       [5, 8]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 8]], dtype=int32)>

In [8]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having two dimensions
matrix1.ndim

2

In [9]:
# Create another matrix
matrix2 = tf.constant([[2., 3.],
                       [4., 5.],
                       [6., 7.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float16)>

In [10]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a flat rectangle in space having two dimensions
matrix2.ndim

2

In [11]:
# Create a tensor
tensor1 = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [9, 8, 7]],
                      [[6, 5, 4],
                       [3, 2, 1]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [3, 2, 1]]], dtype=int32)>

In [12]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 2 and hight (or number of elements with rows and columns) = 3.
tensor1.ndim

3

In [13]:
tensor2 = tf.constant([[[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.]],
                       [[9., 8., 7.],
                        [6., 5., 4.],
                        [3., 2., 1.]],
                       [[9., 6., 3.],
                        [8., 5., 2.],
                        [7., 4., 1.]]])
tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]],

       [[9., 6., 3.],
        [8., 5., 2.],
        [7., 4., 1.]]], dtype=float32)>

In [14]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 3 and hight (or number of elements with rows and columns) = 3.
tensor2.ndim

3

#### Create Tensors from Variables
When we create tensors with variables, we can change values of one or more elements of the tensor subsequently.

In [15]:
# Let's create a vector similar to the one we created before, but this time using tf.Variable
vector1 = tf.Variable([3, 5])
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5], dtype=int32)>

In [16]:
# Change the 2nd element of the vector
vector1[1].assign(8)
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 8], dtype=int32)>

#### Create Random Tensors
Random tensors are tensors of any given size containing random numbers.

In [17]:
# Create a random tensor with 3 rows and 2 columns filled with random normally distributed numbers
rt_1 = tf.random.Generator.from_seed(42)
rt_1 = rt_1.normal(shape=(3, 2))
rt_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
# Create another random tensor, using same random seed ensures the values of the first 2 columns of all 3 rows of this tensor is the same to
# the other tensor we created above inspite of using random numbers to fill the values.
rt_2 = tf.random.Generator.from_seed(42)
rt_2 = rt_2.normal(shape= (3, 3))
rt_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

#### Shuffle the order of elements in a tensor

In [19]:
# Here the second tensor is a randomly shuffled copy of the first tensor.
# The random shuffle operates on the first dimension, which is the 3 rows as found in shape(3, 2).
# However the shuffle occurs every time we run the code
matrix3 = tf.constant([[1, 2],
                       [3, 4],
                       [5, 6]])
matrix4 = tf.random.shuffle(matrix3)
matrix4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [20]:
# Here we create another tensor by suffling the same original tensor. The values get shuffled in the output tensor
# However unlike the above example here the values of the output tensor remains same regardless of how many times we run the code.
# This happens because of setting the random seed to ensure reproducability.
tf.random.set_seed(42)
matrix5 = tf.random.shuffle(matrix3)
matrix5

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

### Getting information from tensors
In this section we will find out different features or attributes of tensors, such as -
* Rank
* Shape
* Size
* Dimensions

In [21]:
# First lets create a 4 dimensional tensor with 1s
t1 = tf.ones(shape=(2, 3, 4, 5))
t1

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [22]:
# Rank of the tensor, or identify a given element in the tensor
t1[1,1,1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [23]:
# Shape of the tensor
t1.shape

TensorShape([2, 3, 4, 5])

In [24]:
# Size of the tensor
size = tf.size(t1).numpy()
size

120

In [25]:
# Dimension of tensor
dim = t1.ndim
dim

4

In [26]:
# Find the first element of the first dimention of the tensor, the result is a 3 dimentional tensor
t1[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [27]:
t1[1, 2]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
# Find 1 item form 1st, 2 items from 2nd, 3 items from 3rd and 4 items from 4th dimention
t1[:1, :2, :3, :4]

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [29]:
# Find last 2 elements from each dimention
t1[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

#### Reshaping tensor
Here we will change the shape of the tensor.

In [30]:
t1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]], dtype=tf.float16)
t1, t1.ndim

(<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float16)>,
 2)

In [31]:
t2 = tf.reshape(t1, [3, 2])
t2, t2.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>,
 2)

In [32]:
t3 = tf.reshape(t1, shape=(6))
t3, t3.ndim

(<tf.Tensor: shape=(6,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float16)>,
 1)

In [33]:
t4 = tf.transpose(t1)
t4, t4.ndim

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=float16)>,
 2)

From the above two codes we can see the `tf.transpose` is changing the shape of the tensor by flipping the rows and columns. Whereas with `tf.reshape` the new shape is filled based on the sequence of values in the original tensor. And `tf.reshape` allows us to even change dimension of a tensor.
### Updating Tensors
In this section we will see how to update values in tensor using mathematical operations such as addition, multiplication, etc.

In [34]:
# Addition
t2 = tf.constant([[3, 4],
                  [6, 7]])
t2 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [16, 17]], dtype=int32)>

In [35]:
# Multiplication using tensorflow's built-in function
t3 = tf.multiply(t2, 10)
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [60, 70]], dtype=int32)>

#### Matrix Multiplication / Dot Product
In this section we will see how to multiply two matrix through few examples by using the following functions -
* `tf.matmul()`
* `tf.tensordot()`

In [36]:
# Create 2 tensors of same shape
t1 = tf.constant([[2, 3],
                  [4, 5]])
t2 = tf.constant([[6, 7],
                  [8, 9]])
t1, t2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 7],
        [8, 9]], dtype=int32)>)

In [37]:
# Element Multiplication - where we multiply each element of the first matrix with the corresponding element of the second matrix
t3 = t1 * t2
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 21],
       [32, 45]], dtype=int32)>

In [38]:
# Matrix multiplication
t4 = tf.matmul(t1, t2)
t4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 41],
       [64, 73]], dtype=int32)>

In [39]:
t5 = tf.constant([[1, 2],
                  [7, 2],
                  [3, 3]])
t6 = tf.constant([[3, 5],
                  [6, 7],
                  [1, 8]])
t5, t6

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [41]:
# Let's try matrix multiplication with these 2 matrix
t7 = tf.matmul(t5, t6)
t7

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [42]:
# The above operation throws error saying 'Matrix size-incompatible'. So let's reshape the first matrix
t5 = tf.constant([[1, 2, 5],
                  [7, 2, 1],
                  [3, 3, 3]])
t5, t6

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [43]:
# Now let's try the same matrix multiplication again
t7 = tf.matmul(t5, t6)
t7

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [44]:
# Now let's try the same matrix multiplication again using `tf.tensordot` method
t8 = tf.tensordot(t5, t6, axes=1)
t8

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

From the above code we see that both `tf.matmul` and `tf.tensordot` gave same multiplication output on our 2 matrixs. However let's explore few more use cases of `tf.tensordot`.

In [45]:
t10 = tf.constant([[2, 3],
                   [4, 5]])
t11 = tf.constant([[6, 7],
                   [8, 9]])
t12 = tf.matmul(t10, t11)
t13 = tf.tensordot(t10, t11, axes=1)
t14 = tf.tensordot(t10, t11, axes=0)
t15 = tf.tensordot(t10, t11, axes=[1, 0])

print("First Input Tensor:")
print(t10)
print("\n")
print("Second Input Tensor:")
print(t11)
print("\n")
print("Resulting Tensor using tf.mutmul:")
print(t12)
print("\n")
print("Resulting Tensor using tf.tensordot using axis 1:")
print(t13)
print("\n")
print("Resulting Tensor using tf.tensordot using axis 0:")
print(t14)
print("\n")
print("Resulting Tensor using tf.tensordot using axis [1, 0]:")
print(t15)

First Input Tensor:
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


Second Input Tensor:
tf.Tensor(
[[6 7]
 [8 9]], shape=(2, 2), dtype=int32)


Resulting Tensor using tf.mutmul:
tf.Tensor(
[[36 41]
 [64 73]], shape=(2, 2), dtype=int32)


Resulting Tensor using tf.tensordot using axis 1:
tf.Tensor(
[[36 41]
 [64 73]], shape=(2, 2), dtype=int32)


Resulting Tensor using tf.tensordot using axis 0:
tf.Tensor(
[[[[12 14]
   [16 18]]

  [[18 21]
   [24 27]]]


 [[[24 28]
   [32 36]]

  [[30 35]
   [40 45]]]], shape=(2, 2, 2, 2), dtype=int32)


Resulting Tensor using tf.tensordot using axis [1, 0]:
tf.Tensor(
[[36 41]
 [64 73]], shape=(2, 2), dtype=int32)


Two important rules of matrix multiplication -
* The number of columns in the first matrix should be the same as the number of rows in the second matrix.
* The resulting matrix will have number of rows same as that of the first matrix and number of columns same as that of the second matrix.

#### Changing the Data Type of Tensor

In [46]:
t1 = tf.constant([3, 5])
t1.dtype

tf.int32

In [47]:
t2 = tf.constant([1.5, 3.8])
t2.dtype

tf.float32

In [48]:
t3 = tf.constant([5, 7.3])
t3, t3.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5. , 7.3], dtype=float32)>,
 tf.float32)

In the above example, we passed one integer (5) and one float (7.3) to create the t3 tensor. The tensor was created as float32 and the integer value was converetd to float32.

In [49]:
# Let's convert the first tensor from integer to float
t4 = tf.cast(t1, dtype=tf.float32)
t4, t4.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>,
 tf.float32)

In [50]:
# Let's convert the above tensor from float32 to float16
# Note that we can also convert int tensor to float16 directly
t5 = tf.cast(t4, dtype=tf.float16)
t5.dtype

tf.float16

The above operation of reducing from float32 to float16 is also known as **Reduced Precision**. By reducing the precision, it helps to reduce the amount of space it take in the memory to store and perform operation with the tensor using **Graphical Processing Units or GPUs**.

### Aggregating Tensors
In this section, we are going to perform following types of aggregation with tensors.
* Find the maximum value in a tensor
* Find the minimum value in a tensor
* Find the mean value in a tensor
* Find the variance in a tensor
* Find the standard deviation in a tensor
* Find the sum of all values in a tensor
* Find the position of the maximum value in a tensor
* Find the position of the minimum value in a tensor

In [51]:
# Create a tensor with 50 random numbers between 0 and 100
t20 = tf.constant(np.random.randint(0, 100, 50))
t20

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91, 40, 58, 51,  9, 93, 54,  8, 82, 31, 86, 41, 21, 21, 98, 12, 46,
       78, 82, 33,  4, 77, 24, 76, 33, 78, 99, 46, 34, 41, 91, 75, 23, 88,
       41, 13,  3, 53, 39, 71, 56, 90,  8, 80, 89, 57, 97, 31, 96, 43])>

In [52]:
# Find the minimum value in a tensor
min = tf.reduce_min(t20).numpy()
min

3

In [53]:
# Find the maximum, mean and sum value in a tensor
max = tf.reduce_max(t20).numpy()
mean = tf.reduce_mean(t20).numpy()
sum = tf.reduce_sum(t20).numpy()
print("Maximum value in a tensor: ", max)
print("Mean value in a tensor: ", mean)
print("Sum of all values in a tensor: ", sum)
#print("Variance in a tensor: ", var)
#print("Standard deviation in a tensor: ", std)

Maximum value in a tensor:  99
Mean value in a tensor:  53
Sum of all values in a tensor:  2691


In [55]:
# Find the variance in a tensor
var = tf.math.reduce_variance(t20)

TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [56]:
# Analyzing the above error we realize that the variance function will work on complex datatype such as float,
# whereas our tesor is of datatype int. So we need to first change the datatype
t21 = tf.cast(t20, dtype=tf.float16)
var = tf.math.reduce_variance(t21).numpy()
var

881.5

In [57]:
# Find the standard deviation in a tensor
std = tf.math.reduce_std(t21).numpy()
std

29.69

In [58]:
# Let's calculate variance and standard deviation on couple of other tensors
t22 = tf.constant([1,2,3,8,9,10], dtype=tf.float16)
t23 = tf.constant([[1,2,3],
                   [8,9,10]], dtype=tf.float16)
print("First tensor: ", t22)
print("\nSecond tensor: ", t23)

var1 = tf.math.reduce_variance(t22).numpy()
print("\nVariance of the first tensor: ", var1)
std1 = tf.math.reduce_std(t22).numpy()
print("\nStandard deviation of the first tensor: ", std1)

var2 = tf.math.reduce_variance(t23).numpy()
print("\nVariance of the second tensor: ", var2)
std2 = tf.math.reduce_std(t23).numpy()
print("\nStandard deviation of the second tensor: ", std2)

First tensor:  tf.Tensor([ 1.  2.  3.  8.  9. 10.], shape=(6,), dtype=float16)

Second tensor:  tf.Tensor(
[[ 1.  2.  3.]
 [ 8.  9. 10.]], shape=(2, 3), dtype=float16)

Variance of the first tensor:  12.914

Standard deviation of the first tensor:  3.594

Variance of the second tensor:  12.914

Standard deviation of the second tensor:  3.594


#### Find the position of the maximum and minimum value in a tensor

In [62]:
# Create a tensor with 50 uniformly distributed decimal numbers
tf.random.set_seed(42)
t30 = tf.random.uniform(shape=[50])
t30

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [64]:
# Find the position of the maximum value in a tensor
pmax = tf.argmax(t30).numpy()
print("Position of the maximum value in the given tensor is: ", pmax)

# Find the maximum value through the position
vmax1 = t30[tf.argmax(t30)].numpy()
print("\nMaximum value in the given tensor is: ", vmax1)

# Find the maximum value through conventional way
vmax2 = tf.math.reduce_max(t30).numpy()
print("\nMaximum value in the given tensor is: ", vmax2)

Position of the maximum value in the given tensor is:  42

Maximum value in the given tensor is:  0.9671384

Maximum value in the given tensor is:  0.9671384


In [66]:
# Find the position of the minimum value in a tensor
pmin = tf.argmin(t30).numpy()
print("Position of the minimum value in the given tensor is: ", pmin)

# Find the minimum value through the position
vmin1 = t30[tf.argmin(t30)].numpy()
print("\nMinimum value in the given tensor is: ", vmin1)

# Find the minimum value through conventional way
vmin2 = tf.math.reduce_min(t30).numpy()
print("\nMinimum value in the given tensor is: ", vmin2)

Position of the minimum value in the given tensor is:  16

Minimum value in the given tensor is:  0.009463668

Minimum value in the given tensor is:  0.009463668


So from the above code example we see that both the `tf.math.reduce_variance()` and `tf.math.reduce_std()` functions produces the same result for both t22 and t23 tensors. Both had same values but t22 was one dimentional / scaler, whereas t23 was two dimentional / vector. That indicates both the `tf.math.reduce_variance()` and `tf.math.reduce_std()` functions reduce n-dimentional tensor into 1 dimentional / flat tensor in otder to derive the variance and standard deviation.