<a href="https://colab.research.google.com/github/GoAshim/Deep-Learning-with-TensorFlow/blob/main/02_Fundamentals_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals of TensorFlow
In this workbook we will not do any project, rather we will work on the fundamental concepts of Tensors using TensorFlow, which is going to help us when we do various Deep Learning projects using Neural Network in TensorFlow in the future workbooks.

We will cover the following concepts in this workbook -
* Introduction to tensors
* Getting information from tensors
* Updating / changing tensors
* Comparing tensor & numpy
* Using @tf function to speed up regular python function
* Using GPU (or TPU) with TensorFlow

### Introduction to tensors
In this section we will explore different ways of creating tensors.

In [1]:
# Import library
import numpy as np
import tensorflow as tf

In [2]:
# Check the current version (as of Feb 3, 2024) of tensorflow
ver = tf.__version__
print(ver)

2.15.0


#### Create Tensors from Constants `tf.constant()`

In [3]:
# Create a single value (scalar) constant tensor with value as numpy integer
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
# We see that it's a zero dimension tensor, meaning one constant value is like a point in space having zero dimension
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([3, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [6]:
# We see that it's a one dimension tensor, meaning an array is like a line in space having one dimension
vector.ndim

1

In [7]:
# Create a matrix
matrix1 = tf.constant([[2, 4],
                       [5, 8]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 8]], dtype=int32)>

In [8]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having two dimensions
matrix1.ndim

2

In [9]:
# Create another matrix
matrix2 = tf.constant([[2., 3.],
                       [4., 5.],
                       [6., 7.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float16)>

In [10]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a flat rectangle in space having two dimensions
matrix2.ndim

2

In [11]:
# Create a tensor
tensor1 = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [9, 8, 7]],
                      [[6, 5, 4],
                       [3, 2, 1]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [3, 2, 1]]], dtype=int32)>

In [12]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 2 and hight (or number of elements with rows and columns) = 3.
tensor1.ndim

3

In [13]:
tensor2 = tf.constant([[[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.]],
                       [[9., 8., 7.],
                        [6., 5., 4.],
                        [3., 2., 1.]],
                       [[9., 6., 3.],
                        [8., 5., 2.],
                        [7., 4., 1.]]])
tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]],

       [[9., 6., 3.],
        [8., 5., 2.],
        [7., 4., 1.]]], dtype=float32)>

In [14]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 3 and hight (or number of elements with rows and columns) = 3.
tensor2.ndim

3

#### Create Tensors from Variables
When we create tensors with variables, we can change values of one or more elements of the tensor subsequently.

In [15]:
# Let's create a vector similar to the one we created before, but this time using tf.Variable
vector1 = tf.Variable([3, 5])
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5], dtype=int32)>

In [16]:
# Change the 2nd element of the vector
vector1[1].assign(8)
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 8], dtype=int32)>

#### Create Random Tensors
Random tensors are tensors of any given size containing random numbers.

In [17]:
# Create a random tensor with 3 rows and 2 columns filled with random normally distributed numbers
rt_1 = tf.random.Generator.from_seed(42)
rt_1 = rt_1.normal(shape=(3, 2))
rt_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
# Create another random tensor, using same random seed ensures the values of the first 2 columns of all 3 rows of this tensor is the same to
# the other tensor we created above inspite of using random numbers to fill the values.
rt_2 = tf.random.Generator.from_seed(42)
rt_2 = rt_2.normal(shape= (3, 3))
rt_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

#### Shuffle the order of elements in a tensor

In [19]:
# Here the second tensor is a randomly shuffled copy of the first tensor.
# The random shuffle operates on the first dimension, which is the 3 rows as found in shape(3, 2).
# However the shuffle occurs every time we run the code
matrix3 = tf.constant([[1, 2],
                       [3, 4],
                       [5, 6]])
matrix4 = tf.random.shuffle(matrix3)
matrix4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [20]:
# Here we create another tensor by suffling the same original tensor. The values get shuffled in the output tensor
# However unlike the above example here the values of the output tensor remains same regardless of how many times we run the code.
# This happens because of setting the random seed to ensure reproducability.
tf.random.set_seed(42)
matrix5 = tf.random.shuffle(matrix3)
matrix5

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

### Getting information from tensors
In this section we will find out different features or attributes of tensors, such as -
* Rank
* Shape
* Size
* Dimensions

In [21]:
# First lets create a 4 dimensional tensor with 1s
t1 = tf.ones(shape=(2, 3, 4, 5))
t1

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [22]:
# Rank of the tensor, or identify a given element in the tensor
t1[1,1,1]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 1., 1., 1., 1.], dtype=float32)>

In [23]:
# Shape of the tensor
t1.shape

TensorShape([2, 3, 4, 5])

In [24]:
# Size of the tensor
size = tf.size(t1).numpy()
size

120

In [25]:
# Dimension of tensor
dim = t1.ndim
dim

4

In [26]:
# Find the first element of the first dimention of the tensor, the result is a 3 dimentional tensor
t1[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [27]:
t1[1, 2]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [28]:
# Find 1 item form 1st, 2 items from 2nd, 3 items from 3rd and 4 items from 4th dimention
t1[:1, :2, :3, :4]

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [29]:
# Find last 2 elements from each dimention
t1[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

#### Reshape tensor
Here we will change the shape of the tensor.

In [37]:
t1 = tf.constant([[1, 2, 3],
                  [4, 5, 6]], dtype=tf.float16)
t1

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [40]:
t2 = tf.reshape(t1, [3, 2])
t2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

### Updating Tensors
In this section we will see how to update values in tensor using mathematical operations such as addition, multiplication, etc.

In [30]:
# Addition
t2 = tf.constant([[3, 4],
                  [6, 7]])
t2 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 14],
       [16, 17]], dtype=int32)>

In [31]:
# Multiplication using tensorflow's built-in function
t3 = tf.multiply(t2, 10)
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [60, 70]], dtype=int32)>

#### Matrix Multiplication
In this section we will see how to multiply two matrix through couple of examples.

In [32]:
# Create 2 tensors of same shape
t1 = tf.constant([[2, 3],
                  [4, 5]])
t2 = tf.constant([[6, 7],
                  [8, 9]])
t1, t2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 7],
        [8, 9]], dtype=int32)>)

In [33]:
# Element Multiplication - where we multiply each element of the first matrix with the corresponding element of the second matrix
t3 = t1 * t2
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 21],
       [32, 45]], dtype=int32)>

In [34]:
# Matrix multiplication
t4 = tf.matmul(t1, t2)
t4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[36, 41],
       [64, 73]], dtype=int32)>

In [35]:
t5 = tf.constant([[1, 2],
                  [7, 2],
                  [3, 3]])
t6 = tf.constant([[3, 5],
                  [6, 7],
                  [1, 8]])
t5, t6

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [36]:
# Let's try matrix multiplication with these 2 matrix
t7 = tf.matmul(t5, t6)
t7

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# The above operation throws error saying 'Matrix size-incompatible'. So let's reshape the first matrix
t5 = tf.constant([[1, 2, 5],
                  [7, 2, 1],
                  [3, 3, 3]])
t5, t6

In [ ]:
# Now let's try the same matrix multiplication again
t7 = tf.matmul(t5, t6)
t7

From the above examples, we find two important rules of matrix multiplication -
* The number of columns in the first matrix should be the same as the number of rows in the second matrix.
* The resulting matrix will have number of rows same as that of the first matrix and number of columns same as that of the second matrix.