<a href="https://colab.research.google.com/github/GoAshim/Deep-Learning-with-TensorFlow/blob/main/02_Fundamentals_of_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Fundamentals of TensorFlow
In this workbook we will not do any project, rather we will work on the fundamental concepts of Tensors using TensorFlow, which is going to help us when we do various Deep Learning projects using Neural Network in TensorFlow in the future workbooks.

We will cover the following concepts in this workbook -
* Introduction to tensors
* Getting information from tensors
* Updating / changing tensors
* Comparing tensor & numpy
* Using @tf function to speed up regular python function
* Using GPU (or TPU) with TensorFlow

### Introduction to tensors

In [2]:
# Import library
import numpy as np
import tensorflow as tf

In [3]:
# Check the current version (as of Feb 3, 2024) of tensorflow
ver = tf.__version__
print(ver)

2.15.0


### Create Tensors from Constants `tf.constant()`

In [4]:
# Create a single value (scalar) constant tensor with value as numpy integer
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [5]:
# We see that it's a zero dimension tensor, meaning one constant value is like a point in space having zero dimension
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([3, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [7]:
# We see that it's a one dimension tensor, meaning an array is like a line in space having one dimension
vector.ndim

1

In [8]:
# Create a matrix
matrix1 = tf.constant([[2, 4],
                       [5, 8]])
matrix1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 8]], dtype=int32)>

In [9]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having two dimensions
matrix1.ndim

2

In [10]:
# Create another matrix
matrix2 = tf.constant([[2., 3.],
                       [4., 5.],
                       [6., 7.]], dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float16)>

In [11]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a flat rectangle in space having two dimensions
matrix2.ndim

2

In [12]:
# Create a tensor
tensor1 = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [9, 8, 7]],
                      [[6, 5, 4],
                       [3, 2, 1]]])
tensor1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [3, 2, 1]]], dtype=int32)>

In [13]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 2 and hight (or number of elements with rows and columns) = 3.
tensor1.ndim

3

In [14]:
tensor2 = tf.constant([[[1., 2., 3.],
                        [4., 5., 6.],
                        [7., 8., 9.]],
                       [[9., 8., 7.],
                        [6., 5., 4.],
                        [3., 2., 1.]],
                       [[9., 6., 3.],
                        [8., 5., 2.],
                        [7., 4., 1.]]])
tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]],

       [[9., 6., 3.],
        [8., 5., 2.],
        [7., 4., 1.]]], dtype=float32)>

In [15]:
# We see that it's a two dimension tensor, meaning a two dimensional array is like a rectangular shape in space having three dimensions.
# It has length (or number of columns) = 3, # width (or number of rows) = 3 and hight (or number of elements with rows and columns) = 3.
tensor2.ndim

3

### Create Tensors from Variables
When we create tensors with variables, we can change values of one or more elements of the tensor subsequently.

In [16]:
# Let's create a vector similar to the one we created before, but this time using tf.Variable
vector1 = tf.Variable([3, 5])
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 5], dtype=int32)>

In [18]:
# Change the 2nd element of the vector
vector1[1].assign(8)
vector1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 8], dtype=int32)>

### Create Random Tensors
Random tensors are tensors of any given size containing random numbers.

In [21]:
# Create a random tensor with 3 rows and 2 columns filled with random normally distributed numbers
rt_1 = tf.random.Generator.from_seed(42)
rt_1 = rt_1.normal(shape=(3, 2))
rt_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
# Create another random tensor, using same random seed ensures the values of the first 2 columns of all 3 rows of this tensor is the same to
# the other tensor we created above inspite of using random numbers to fill the values.
rt_2 = tf.random.Generator.from_seed(42)
rt_2 = rt_2.normal(shape= (3, 3))
rt_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>